### ISSUE TITLE
French Assistant Computer Control

### ISSUE THREAD

**Issue by FazCodeFR** [dsoiM/googlehomePCPOSH#2]
French Assistant Computer Control
Here is a quick and complete french alternative
We can cooperate if you agree.
https://www.youtube.com/watch?v=-Z2OFYVMIKk
https://github.com/ABOATDev/Control-Google-Home/

**Comment by dsoiM** [comment]
Hi,
looks interesting! Though it is vbscript and works in a bit different ways. How were you thinking cooperation?

**Comment by FazCodeFR** [comment]
Hi sorry for the response time 
I will contact you very soon
I thought English/French translation system 
Can you code in vbs? my project is based on vbs mainly

**Comment by dsoiM** [comment]
Our projects are quite different as this one provide abstraction for any command the user wants to do in PowerShell. Your project aims for a built-in feature set with strict set of keywords. Also I have no interest in vbs and it is not easily user acccessible for the purposes what this project is for. Sorry but I'm afraid we should not join forces
